### ISSUE TITLE
Deeplink with parameters

### ISSUE THREAD

**Issue by vipulbuoyancy** [VaheSaroyan/react-native-boilerplate#31]
Hello Sir,

Please help me with the opening app with deep link and parameters using query string.

Thank you.

**Comment by VaheSaroyan** [comment]
@vipulbuoyancy what issue?

**Comment by vipulbuoyancy** [comment]
I am able to open the application using the deep link & custom scheme, But it is not getting redirected to appropriate route also I am not getting the values which I am passing to query string. Can you please help me with how to get values of querystring?

**Comment by VaheSaroyan** [comment]
In my opinion, you will help this
`useEffect(() => {
    Linking.getInitialURL()
      .then(url => {
        if (url) {
          setUlink(url);
        }
      })
      .catch(e => logger.err(e));
    Linking.addEventListener('url', appUp);

    return () => Linking.removeEventListener('url', appUp);
  }, []);`
  
  
`  useEffect(() => {
    if (ulink) {
      routeByLink(ulink);
      setUlink('');
    }
  }, [ulink]);`
  
  
` URLEntry(url: string): URLEntry {
    setupURLPolyfill();
    const entryPoint = new URL(url);
    const entry = entryPoint.pathname;

    const publicKey = entryPoint.searchParams.get('public_key') || '';
    const privateKey = entryPoint.searchParams.get('private_key') || '';

    return {
      path: entry,
      publicKey,
      privateKey,
    };
  }
}`

`export const routeByLink = async (URL:string) =>{
  const { ...params } = URLEntry(url);
}`

**Comment by vipulbuoyancy** [comment]
Thank you so much @VaheSaroyan. I am quite new to React Native, can you please help me with where should I try this code? means in which file?

**Comment by VaheSaroyan** [comment]
In your root navigation file
